server:
  port: 8081
spring:
  application:
    name: terminal
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/terminal?createDatabaseIfNotExist=true
    username: ${SCHEMA_USERNAME}
    password: ${SCHEMA_PASSWORD}
  jpa:
    show-sql: true
